# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tctp.proto\x12\x03\x63tp\" \n\x10\x41ppendRunRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"#\n\x11\x41ppendRunResponse\x12\x0e\n\x06run_id\x18\x01 \x01(\x03\"-\n\rGetRunRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x65xp_id\x18\x02 \x01(\x03\" \n\x0eGetRunResponse\x12\x0e\n\x06run_id\x18\x01 \x01(\x03\x32{\n\nCtpService\x12:\n\tAppendRun\x12\x15.ctp.AppendRunRequest\x1a\x16.ctp.AppendRunResponse\x12\x31\n\x06GetRun\x12\x12.ctp.GetRunRequest\x1a\x13.ctp.GetRunResponseb\x06proto3')



_APPENDRUNREQUEST = DESCRIPTOR.message_types_by_name['AppendRunRequest']
_APPENDRUNRESPONSE = DESCRIPTOR.message_types_by_name['AppendRunResponse']
_GETRUNREQUEST = DESCRIPTOR.message_types_by_name['GetRunRequest']
_GETRUNRESPONSE = DESCRIPTOR.message_types_by_name['GetRunResponse']
AppendRunRequest = _reflection.GeneratedProtocolMessageType('AppendRunRequest', (_message.Message,), {
  'DESCRIPTOR' : _APPENDRUNREQUEST,
  '__module__' : 'ctp_pb2'
  # @@protoc_insertion_point(class_scope:ctp.AppendRunRequest)
  })
_sym_db.RegisterMessage(AppendRunRequest)

AppendRunResponse = _reflection.GeneratedProtocolMessageType('AppendRunResponse', (_message.Message,), {
  'DESCRIPTOR' : _APPENDRUNRESPONSE,
  '__module__' : 'ctp_pb2'
  # @@protoc_insertion_point(class_scope:ctp.AppendRunResponse)
  })
_sym_db.RegisterMessage(AppendRunResponse)

GetRunRequest = _reflection.GeneratedProtocolMessageType('GetRunRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETRUNREQUEST,
  '__module__' : 'ctp_pb2'
  # @@protoc_insertion_point(class_scope:ctp.GetRunRequest)
  })
_sym_db.RegisterMessage(GetRunRequest)

GetRunResponse = _reflection.GeneratedProtocolMessageType('GetRunResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETRUNRESPONSE,
  '__module__' : 'ctp_pb2'
  # @@protoc_insertion_point(class_scope:ctp.GetRunResponse)
  })
_sym_db.RegisterMessage(GetRunResponse)

_CTPSERVICE = DESCRIPTOR.services_by_name['CtpService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _APPENDRUNREQUEST._serialized_start=18
  _APPENDRUNREQUEST._serialized_end=50
  _APPENDRUNRESPONSE._serialized_start=52
  _APPENDRUNRESPONSE._serialized_end=87
  _GETRUNREQUEST._serialized_start=89
  _GETRUNREQUEST._serialized_end=134
  _GETRUNRESPONSE._serialized_start=136
  _GETRUNRESPONSE._serialized_end=168
  _CTPSERVICE._serialized_start=170
  _CTPSERVICE._serialized_end=293
# @@protoc_insertion_point(module_scope)
